services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Etc/UTC
      WATCHTOWER_LIFECYCLE_HOOKS: True
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: telegram://BOT_TOKEN@telegram/?channels=CHAT_ID
      WATCHTOWER_DEBUG: True
      WATCHTOWER_CLEANUP: True
      WATCHTOWER_SCHEDULE: 0 0 0 * * *
