services:
  LB:
    image: haproxy:latest
    container_name: LB
    restart: always
    ports:
      - "0.0.0.0:1111:1111"
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/dhparam.pem:/etc/haproxy/dhparam.pem:ro
      - ./certs/fullchain.cer:/etc/haproxy/fullchain.cer:ro
      - ./certs/fullchain.key:/etc/haproxy/fullchain.key:ro
